### PR TITLE
WIP: In zktrie, support SELFDESTRUCT op 

### PR DESCRIPTION
**Pull request by noel2004**
Currently zktrie detour any `delete` requrest into an updating with 32 bytes of zero. As the result, when an account object is deleted, it would be updated into some bytes which cound not be unmarshalled and a permanent error would be left in database.

The correct behavior has been implied in zktrie while it still require more solid testing. As a compromise, this PR induce part of the deleting action: only update the corresponding leaf node to empty node, while no reorganiztion on the path would occur. So the new code involved could be checked more easily.

The mptwiness generator is also updated to support `selfdestruct` op.

I also has updated all the trace examples in zkproof module, which was broken by PR #133

### CODE REVIEW

**Comment by lispc** [comment]
Any thing will be broken if we merge this pr？or can we just merge it and redeploy l2geth in our testnet？

**Comment by noel2004** [comment]
For some edge cases I have considered today, now I prone to delay this work and move some work into `fix/failed` branch first. The witness for selfdestruct may be affected by an issue found in rw_table and later I will post it.

**Comment by noel2004** [comment]
I may give up current implement and wait for https://github.com/scroll-tech/zkevm-circuits/issues/189 being resolved or the spec has been updated.

**Comment by 0xmountaintop** [comment]
should we close this PR if we are going to disable `SELFDESTRUCT`?

**Comment by noel2004** [comment]
> should we close this PR if we are going to disable `SELFDESTRUCT`?

Agree. And some useful work in this PR has been moved to #146 now.

**Pull request closed without merging**
