### PR TITLE
make l2geth arm64 compatible

### PR DESCRIPTION
**Pull request by sbaizet-ledger**
## 1. Purpose or design rationale of this PR

Make our l2geth image arm64 compatible

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [ ] build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- [X] ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- [ ] docs: Documentation-only changes
- [ ] feat: A new feature
- [ ] fix: A bug fix
- [ ] perf: A code change that improves performance
- [ ] refactor: A code change that doesn't fix a bug, or add a feature, or improves performance
- [ ] style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] test: Adding missing tests or correcting existing tests

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [ ] This PR doesn't involve a new deployment, git tag, docker image tag, and it doesn't affect traces
- [ ] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [ ] This PR is not a breaking change
- [ ] Yes

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
should we also change to go-1.21?

**Comment by 0xmountaintop** [comment]
this build runs for a long time, and one of the reasons is it re-downloads `2022-12-10` rust toolchain

I think you will need to update `rollup/circuitcapacitychecker/libzkp/rust-toolchain` file

**Comment by johnsonjie** [comment]
> should we also change to go-1.21?

we can change this if you need, @Thegaram  can you confirm this?

**Comment by johnsonjie** [comment]
> this build runs for a long time, and one of the reasons is it re-downloads `2022-12-10` rust toolchain
> 
> I think you will need to update `rollup/circuitcapacitychecker/libzkp/rust-toolchain` file

why this re-download happened? It's too old and need updating?

**Comment by 0xmountaintop** [comment]
> > this build runs for a long time, and one of the reasons is it re-downloads `2022-12-10` rust toolchain
> > I think you will need to update `rollup/circuitcapacitychecker/libzkp/rust-toolchain` file
> 
> why this re-download happened? It's too old and need updating?

`rollup/circuitcapacitychecker/libzkp/rust-toolchain` will specify a version to use.
if builder image is based on 2023-12-03, then it mismatches `rollup/circuitcapacitychecker/libzkp/rust-toolchain`
then cargo will download the one specified in `rollup/circuitcapacitychecker/libzkp/rust-toolchain`

**Comment by 0xmountaintop** [comment]
> > should we also change to go-1.21?
> 
> we can change this if you need, @Thegaram can you confirm this?

let's keep it as go-1.20 for now (I thought @sbaizet-ledger built a go-1.21 image in https://github.com/scroll-tech/scroll)

**Pull request closed without merging**
