### PR TITLE
Fix transaction DA cost under-estimation

### PR DESCRIPTION
**Pull request by Thegaram**
## 1. Purpose or design rationale of this PR

Account for (1) 3-byte-long chain ID, (2) transaction length prefix when calculating DA costs for L2 transactions. For details please see the comments.

References:
- Gas on Optimism: https://hackmd.io/@rajivpoc/SJzAVsB15
- RLP spec: https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp
- Scroll batch encoding: [code](https://github.com/scroll-tech/scroll/blob/f6f11be0cfd1db0da45745f83988f89817ee9994/common/types/batch.go#L168)

## 2. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [ ] This PR doesn't involve a new deployment, git tag, docker image tag, and it doesn't affect traces
- [x] Yes

### CODE REVIEW

**Comment by andyrdt** [comment]
do we need to update the [L1GasPriceOracle](https://github.com/scroll-tech/scroll/blob/develop/contracts/src/L2/predeploys/L1GasPriceOracle.sol#L86) contract as well?  There's a method `getL1Fee` which uses the previous value, I'm not sure when that contract method would actually be used though.

**Comment by maxwolff** [comment]
> do we need to update the [L1GasPriceOracle](https://github.com/scroll-tech/scroll/blob/develop/contracts/src/L2/predeploys/L1GasPriceOracle.sol#L86) contract as well? There's a method `getL1Fee` which uses the previous value, I'm not sure when that contract method would actually be used though.

good idea, we dont actually use that method anywhere, i think its just there for reference, but probably good to change to be consistent

**Comment by 0xmountaintop** [comment]
related: https://github.com/scroll-tech/scroll/pull/498

**Review by 0xmountaintop — DISMISSED** [review]

**Review by icemelon — DISMISSED** [review]

**Review by icemelon — COMMENTED** [review]
I think we should bump up the `patch` version.

**Review by colinlyguo — DISMISSED** [review]

**Comment by icemelon** [comment]
btw. I think this PR cannot be merged before #337 and #342 because the new hardfork version shouldn't include this change.

**Review by 0xmountaintop — APPROVED** [review]

**Pull request merged**
