### PR TITLE
fix: eth_estimateGas error in zero balance address

### PR DESCRIPTION
**Pull request by colinlyguo**
## 1. Purpose or design rationale of this PR

Correct response (Ethereum, account with 0 balance):

```
curl https://mainnet.infura.io/v3/9baa7a0388c9440a85534617d4d862a9 -X POST -H "Content-Type: application/json" --data '{"method":"eth_estimateGas","params":[{"from":"0x8888889C9818892B700e27F316cc3E41e17fBeb9","to":"0x8888889C9818892B700e27F316cc3E41e17fBeb9"}],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"result":"0x5208"}
```

Incorrect response (Scroll, account with 0 balance):

```
curl https://rpc.scroll.io/ -X POST -H "Content-Type: application/json" --data '{"method":"eth_estimateGas","params":[{"from":"0x8888889C9818892B700e27F316cc3E41e17fBeb9","to":"0x8888889C9818892B700e27F316cc3E41e17fBeb9"}],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0x8888889C9818892b700E27f316CC3E41e17fbeb9 have 0 want 75453596795115 (supplied gas 5005617)"}}
```

Root cause:
1. Error msg return path:
a. https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/core/state_transition.go#L243
b. https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/core/state_transition.go#L312
c. https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/core/state_transition.go#L341
d. https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/core/state_transition.go#L205
e. https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/internal/ethapi/api.go#L1003
f. https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/internal/ethapi/api.go#L1176
2. Caused by adding l1 data fee here: https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/core/state_transition.go#L238

No need to check L1 data fee in `DoCall`, because it only checks if the tx can be successfully executed within a specified gas limit.

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] fix: A bug fix

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [ ] This PR doesn't involve a new deployment, git tag, docker image tag, and it doesn't affect traces
- [x] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [x] This PR is not a breaking change
- [ ] Yes

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205740405905906

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
I am not sure whether it's what we want, if a user estimates gas and then uses this gas to call, the call will still fail?

i feel like we can handle this types of error specially (if it's this error type, don't return error in `DoEstimateGas`, but provide the l1fee&l2fee details)

**Comment by mask-pp** [comment]
It works at my local env.

**Review by mask-pp — DISMISSED** [review]

**Comment by colinlyguo** [comment]
> I am not sure whether it's what we want, if a user estimates gas and then uses this gas to call, the call will still fail?
> 
> i feel like we can handle this types of error specially (if it's this error type, don't return error in `DoEstimateGas`, but provide the l1fee&l2fee details)

L1 data fee is `subtracted` here when tx has fees: https://github.com/scroll-tech/go-ethereum/blob/scroll-v5.0.1/internal/ethapi/api.go#L1137-L1145
After `subtraction`, `DoCall` only cares about the L2 fees, which is compatible with semantics in Ethereum. So `preCheck` can ignore L1 data fees.

**Comment by colinlyguo** [comment]
Local test looks good (`eth_call` & `eth_estimateGas`):
```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_call","params":[{"from":"0x8888889C9818892B700e27F316cc3E41e17fBeb9","to":"0x8888889C9818892B700e27F316cc3E41e17fBeb9"}, "latest"],"id":1,"jsonrpc":"2.0"}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   208  100    39  100   169  12400  53736 --:--:-- --:--:-- --:--:--  203k
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x"
}
```

```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_estimateGas","params":[{"from":"0x8888889C9818892B700e27F316cc3E41e17fBeb9","to":"0x8888889C9818892B700e27F316cc3E41e17fBeb9"}],"id":1,"jsonrpc":"2.0"}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   209  100    43  100   166   7742  29888 --:--:-- --:--:-- --:--:-- 69666
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x5208"
}
```

**Comment by mask-pp** [comment]
One situation that should be considered is that l1DataFee is used when running but `eth_estimateGas` doesn't include l1DataFee.

**Comment by mask-pp** [comment]
> It works at my local env.

More complete verification is needed.

**Review by 0xmountaintop — DISMISSED** [review]

**Review by mask-pp — DISMISSED** [review]

**Review by zimpha — APPROVED** [review]

**Review by Thegaram — APPROVED** [review]

**Comment by Thegaram** [comment]
An additional note: `eth_estimateGas` will fail if the account has zero balance but the user provides a gas price:

```
$ curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_estimateGas","params":[{"from":"0x8888889C9818892B700e27F316cc3E41e17fBeb9","to":"0x8888889C9818892B700e27F316cc3E41e17fBeb9", "gasPrice": "0x1"}],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"insufficient funds for l1 fee"}}
```

https://github.com/scroll-tech/go-ethereum/blob/11bf5a904ef70b45ed1a40fe96a3b5448fdee6c0/internal/ethapi/api.go#L1099-L1105

This is consistent with the way that geth handles `value` in this case.

**Comment by colinlyguo** [comment]
> An additional note: `eth_estimateGas` will fail if the account has zero balance but the user provides a gas price:
> 
> ```
> $ curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_estimateGas","params":[{"from":"0x8888889C9818892B700e27F316cc3E41e17fBeb9","to":"0x8888889C9818892B700e27F316cc3E41e17fBeb9", "gasPrice": "0x1"}],"id":1,"jsonrpc":"2.0"}'
> {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"insufficient funds for l1 fee"}}
> ```
> 
> https://github.com/scroll-tech/go-ethereum/blob/11bf5a904ef70b45ed1a40fe96a3b5448fdee6c0/internal/ethapi/api.go#L1099-L1105
> 
> This is consistent with the way that geth handles `value` in this case.

Yeah. Let's consider how to handle this systematically after receiving more feedback. Potential inconsistency with SDKs.

**Pull request merged**
