### PR TITLE
perf(poseidon): eliminate heap allocations in poseidon

### PR DESCRIPTION
**Pull request by omerfirmak**
before:

```
BenchmarkPoseidonHash-11    	   34308	     33968 ns/op	   16920 B/op	     519 allocs/op
```

after:

```
BenchmarkPoseidonHash-11    	   46311	     25037 ns/op	      96 B/op	       2 allocs/op
```

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
so my understanding is

+ we 1) switch from pointer slices to value slices; 2) use fix length slices
+ this can mitigate heap allocation, but there're concerns that 1) it could also introduce larger stack size and increase gc pressure, 2) value copy also introduces overhead 
+ but since the depth is not deep, these tradeoffs are worthy, we don't need to worry about these concerns.

**Comment by omerfirmak** [comment]
> so my understanding is
> 
>     * we 1) switch from pointer slices to value slices; 2) use fix length slices
> 
>     * this can mitigate heap allocation, but there're concerns that 1) it could also introduce larger stack size and increase gc pressure, 2) value copy also introduces overhead
> 
>     * but since the depth is not deep, these tradeoffs are worthy, we don't need to worry about these concerns.

Yes, that is more or less it. But as you can see, pros outweigh the cons, there is a significant speed up.

**Review by lispc — DISMISSED** [review]

**Review by 0xmountaintop — DISMISSED** [review]
this optimization really repends on tree depth, but looks good in our case

**Comment by omerfirmak** [comment]
> this optimization really repends on tree depth

Can you elaborate? I am not sure if I am following.

**Comment by 0xmountaintop** [comment]
> > this optimization really repends on tree depth
> 
> Can you elaborate? I am not sure if I am following.

I mean whether this optimization works depends on the depth, just as described in https://github.com/scroll-tech/go-ethereum/pull/712#issuecomment-2065612887

**Comment by omerfirmak** [comment]
> > > this optimization really repends on tree depth
> > 
> > 
> > Can you elaborate? I am not sure if I am following.
> 
> I mean whether this optimization works depends on the depth, just as described in [#712 (comment)](https://github.com/scroll-tech/go-ethereum/pull/712#issuecomment-2065612887)

Stack size of poseidon is constant (there is no recursion or anything), so it is not dependant on the tree depth.

**Comment by 0xmountaintop** [comment]
yeah I mean, even if it's a constant, if it's a very large constant, let's say 1000, it might turn out to be a "negative optimization"? but that's not the case in our blockchain, so your PR is indeed an optimization.

**Comment by 0xmountaintop** [comment]
nvm, it's just some notes to myself. it doesn't change the fact that it's a good PR.

**Review by 0xmountaintop — APPROVED** [review]

**Review by lispc — APPROVED** [review]

**Pull request merged**
