### PR TITLE
Replace `utesting/blocktraces` with git-submodule `test-traces`

### PR DESCRIPTION
**Pull request by silathdiir**

### CODE REVIEW

**Comment by ChuhanJin** [comment]
Can one of the admins verify this patch?

**Comment by noel2004** [comment]
Would we consider to put more samples (beyond traces for witness generator) in the `test-traces` repo? If so I prefer to organize current traces under a specifield directory (like `mpt_witness`)

**Review by 0xmountaintop — DISMISSED** [review]

**Comment by 0xmountaintop** [comment]
> Would we consider to put more samples (beyond traces for witness generator) in the `test-traces` repo? If so I prefer to organize current traces under a specifield directory (like `mpt_witness`)

OK.


So, @silathdiir please move https://github.com/scroll-tech/test-traces/*.json to https://github.com/scroll-tech/test-traces/mpt_witness/*.json  and update this PR accordingly

**Review by noel2004 — DISMISSED** [review]
Seems everything has been set. All ok.

**Review by 0xmountaintop — APPROVED** [review]

**Review by noel2004 — APPROVED** [review]

**Pull request merged**
