### PR TITLE
feat: disable EIP-2930 && EIP-1559

### PR DESCRIPTION
**Pull request by colinlyguo**
This PR disables EIP-2930 && EIP-1559.

**Implementation**: Disable Berlin Hard Fork and London Hard Fork.

Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930.
London Hard Fork: EIP-1559, EIP-3541, EIP-3554, EIP-3529, EIP-3198.

### CODE REVIEW

**Comment by ChuhanJin** [comment]
Can one of the admins verify this patch?

**Comment by mask-pp** [comment]
> This PR disables EIP-1559, EIP-2778, EIP-2930, to enable legacy type tx only (disable others).
> 
> **Implementation**: Disable Berlin Hard Fork and London Hard Fork.
> 
> Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930. London Hard Fork: EIP-1559, EIP-3238.

**Comment by mask-pp** [comment]
> This PR disables EIP-1559, EIP-2778, EIP-2930, to enable legacy type tx only (disable others).
> 
> **Implementation**: Disable Berlin Hard Fork and London Hard Fork.
> 
> Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930. London Hard Fork: EIP-1559, EIP-3238.

It's necessary to delete the [config fields](https://github.com/scroll-tech/go-ethereum/blob/cdaea939622ef0eaa596f1d13fb5e61b93a5ea2d/params/config.go#L347)?

**Comment by colinlyguo** [comment]
> > This PR disables EIP-1559, EIP-2778, EIP-2930, to enable legacy type tx only (disable others).
> > **Implementation**: Disable Berlin Hard Fork and London Hard Fork.
> > Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930. London Hard Fork: EIP-1559, EIP-3238.
> 
> It's necessary to delete the [config fields](https://github.com/scroll-tech/go-ethereum/blob/cdaea939622ef0eaa596f1d13fb5e61b93a5ea2d/params/config.go#L347)?

`nil = no fork`, thus delete config in `genesis.json` is enough.
ref: https://github.com/scroll-tech/go-ethereum/blob/cdaea939622ef0eaa596f1d13fb5e61b93a5ea2d/params/config.go#L615

**Comment by Thegaram** [comment]
I'll need to read up about those hard forks to see if this is the right approach. But if it is, we should make this change in https://github.com/scroll-tech/testnet, not here.

**Comment by mask-pp** [comment]
> This PR disables EIP-1559, EIP-2778, EIP-2930, to enable legacy type tx only (disable others).
> 
> **Implementation**: Disable Berlin Hard Fork and London Hard Fork.
> 
> Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930. London Hard Fork: EIP-1559, EIP-3238.

I think it should be the code level change, but not in config file.

**Comment by OrestTa** [comment]
@colinlyguo could you share the background rationale for disabling these?

**Comment by colinlyguo** [comment]
> @colinlyguo could you share the background rationale for disabling these?

Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930.
London Hard Fork: EIP-1559, EIP-3541, EIP-3554, EIP-3529, EIP-3198.

EIP-2930 && EIP-1559 are included in the two hard forks.
EIP-2930: disables optional access lists.
EIP-1559: improves the transaction fee market.

**Side effect:** EIP-2565, EIP-2718, EIP-2929, EIP-3541, EIP-3554, EIP-3529, EIP-3198 are also closed.
EIP-2565: changes ModEXP Gas Prices.
EIP-2718: introduces Typed Transaction Envelope.
EIP-2929: increases the gas cost for state access opcodes.
EIP-3541: prevents deploying contracts starting with 0xEF.
EIP-3554: delays the Ice Age until December 2021.
EIP-3529: reduces the gas refunds for EVM.
EIP-3198: returns the base fee from a block.

**Comment by OrestTa** [comment]
> > @colinlyguo could you share the background rationale for disabling these?
> 
> Berlin Hard Fork: EIP-2565, EIP-2718, EIP-2929, EIP-2930. London Hard Fork: EIP-1559, EIP-3541, EIP-3554, EIP-3529, EIP-3198.
> 
> EIP-2930 && EIP-1559 are included in the two hard forks. EIP-2930: disables optional access lists. EIP-1559: improves the transaction fee market.
> 
> **Side effect:** EIP-2565, EIP-2718, EIP-2929, EIP-3541, EIP-3554, EIP-3529, EIP-3198 are also closed. EIP-2565: changes ModEXP Gas Prices. EIP-2718: introduces Typed Transaction Envelope. EIP-2929: increases the gas cost for state access opcodes. EIP-3541: prevents deploying contracts starting with 0xEF. EIP-3554: delays the Ice Age until December 2021. EIP-3529: reduces the gas refunds for EVM. EIP-3198: returns the base fee from a block.

thx!

for other Scrollers, s. also: https://www.notion.so/scrollzkp/Infra-EN-Sync-e1bcc64de42e48669ab0e5b5d41297c8#596d1c8136e64dabb99bf4979a10ee79

**Pull request closed without merging**
