### PR TITLE
fix logs error tracing

### LINKED ISSUE #153: trace seems incorrect
there may be some issue with sync.pool?

block 7871
a uniswap tx reverted

image
There should be an error “out of gas” but there isn't

trace:
https://scrollco.slack.com/files/U02PP3R89HB/F041MHR6WHE/7871.block_result.json

### PR DESCRIPTION
**Pull request by mask-pp**

### CODE REVIEW

**Comment by lispc** [comment]
seems correct!

**Review by lispc — DISMISSED** [review]

**Comment by noel2004** [comment]
It should be noted that:

1. `CaptureState` alway capture the evm state BEFORE the passing `op` argument being executed, more specifily, if the `err` passed in is not nil, it indicate an error occur BEFORE the `op` can be executed, like out of gas/memory, etc.

2.  Any error raised after an opcode is executed cause the EVM exiting from current running and the error is captured in `CaptureFault`, so maybe we should also handle this error?

3. Each call op bring in a new, isolated EVM for the following executions but all the EVMs share the same logger object, so it is highly impossible for the error raised from the EVM in deeper callstack being kept when the execution of tx has finished. Should be record the errorcode in the corresponding CALL op trace instead?

**Comment by noel2004** [comment]
Also, to handle `CaptureFault` we must note that:

The op code passed in `captureFault` should has had its trace being recorded in the logs. However, it is not always the last record in the logs. For any `CALL` op, `captureFault` raised after all the op in the called code being executed (and put into logs). 

We should record the position of op record in `CaptureState` for **every depth**, so we could find the correct position of it in `CaptureFault`, like what we have done for the `CaptureExit`, or we just skip any fault in `CaptureFault` for the call op (they can be handled in `CaptureExit`

**Comment by 0xmountaintop** [comment]
before: https://gist.github.com/HAOYUatHZ/cdac11d38fecf9198aa51b781e33c9f2
after: https://gist.github.com/HAOYUatHZ/fa9b858af62b462e82915d6f8ccabe5f

diff:
```
104952d104951
<         "error":"out of gas",
```

**Comment by 0xmountaintop** [comment]
To summarize @noel2004's idea: 

1. We need to handle `captureFault` because it captures op result failure which `captureState` cannot.
2. We can follow the similar idea in `CaptureExit` to find the failed op position in logs.

The above-mentioned are lacking in this PR. (But we can do these in another PR.)

**Review by 0xmountaintop — APPROVED** [review]

**Comment by mask-pp** [comment]
> To summarize @noel2004's idea:
> 
> 1. We need to handle `captureFault` because it captures op result failure which `captureState` cannot.
> 2. We can follow the similar idea in `CaptureExit` to find the failed op position in logs.
> 
> The above-mentioned are lacking in this PR. (But we can do these in another PR.)

Ok, i get it and will fix finish it in next PR.

**Review by noel2004 — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
tracked in https://github.com/scroll-tech/go-ethereum/issues/155

**Pull request merged**
