### PR TITLE
fix(trace): fix storage proof of l1gas price oracle

### PR DESCRIPTION
**Pull request by noel2004**
The [code here in `api_trace.go`](https://github.com/scroll-tech/go-ethereum/blob/3cf5ba882dd89b5b532341f775dd4bb98db2209a/eth/tracers/api_blocktrace.go#L353) enforce the proof for storage slots in `L1GasPriceOracle` contract being collected:

~~~ go

	proofStorages := tracer.UpdatedStorages()
	proofStorages[rcfg.L1GasPriceOracleAddress] = vm.Storage(
		map[common.Hash]common.Hash{
			rcfg.L1BaseFeeSlot: {}, // notice we do not need the right value here
			rcfg.OverheadSlot:  {},
			rcfg.ScalarSlot:    {},
		})
	for addr, keys := range proofStorages {

~~~

There is an issue: when some slot of `L1GasPriceOracle` is updated in the tx, the code here in fact rewrite the data obtained from `tracer.UpdatedStorages`. For example, if the `slot(0)` of `L1GasPriceOracle` is touched, it would be dropped in the block trace because of the problematic code.

This patch fix the issue above and move all the collection of storage proofs from each evaluation of tx results to the end of filling block result. So we also save a little cost.

### CODE REVIEW

**Review by lispc — DISMISSED** [review]
Seems good. How did you test this?

**Comment by noel2004** [comment]
> Seems good. How did you test this?

May regenerate the bridge trace and check storage trace.

**Comment by lispc** [comment]
> > Seems good. How did you test this?
> 
> May regenerate the bridge trace check storage trace.

ok. we should merge https://github.com/scroll-tech/go-ethereum/pull/367 with this branch, and then use the new commit toregenerate all traces?

**Comment by noel2004** [comment]
> > > Seems good. How did you test this?
> > 
> > 
> > May regenerate the bridge trace check storage trace.
> 
> ok. we should merge #367 with this branch, and then use the new commit toregenerate all traces?

Yes, that should work

**Comment by 0xmountaintop** [comment]
cherry-picked https://github.com/scroll-tech/go-ethereum/pull/367/commits/3f72fc7e257044a01565a4e2093d36619b1b4d33 in https://github.com/scroll-tech/go-ethereum/pull/367

**Review by 0xmountaintop — DISMISSED** [review]

**Review by Thegaram — DISMISSED** [review]

**Review by lispc — DISMISSED** [review]

**Pull request merged**
