### PR TITLE
Upgrade txpool module to increase tps

### PR DESCRIPTION
**Pull request by mask-pp**
More detail please refer the [doc](https://www.notion.so/l2geth-benchmark-test-origin-a1a4a537500b428b9e277bc766d82cfb).

### CODE REVIEW

**Comment by ChuhanJin** [comment]
Can one of the admins verify this patch?

**Review by 0xmountaintop — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
will also be great to record tps before vs after in the PR description

**Comment by mask-pp** [comment]
> will also be great to record tps before vs after in the PR description

ALready added the description！

**Review by hsyodyssey — COMMENTED** [review]
Hi Huan, as I understand it, this PR is trying to reduce GC pressure by reducing the declaration of large data structures, such as `spammers`.  Logically this is very reasonable.

I have a small concern because `spammers` seems like not a thread-safe priority queue. But it seems the txpool will be locked by https://github.com/mask-pp/go-ethereum/blob/up_tps/core/tx_pool.go#L1172?  If so, looks good to me.

**Comment by mask-pp** [comment]
> 

The used place of `pool.spammers` is in [truncatePending](https://github.com/mask-pp/go-ethereum/blob/8c628fc311bc754daf3cb07e23189d8bedbd4c74/core/tx_pool.go#L1212) func, and `truncatePending` locked in the `pool.mu.lock() pool.mu.Unlock()` area. So it's safe.

**Review by hsyodyssey — APPROVED** [review]

**Pull request merged**
