### PR TITLE
refactor: rename `L1FeeEnabled` to `FeeVaultEnabled`

### PR DESCRIPTION
**Pull request by 0xmountaintop**
to address https://github.com/scroll-tech/go-ethereum/pull/262#discussion_r1168781498

### CODE REVIEW

**Review by Thegaram — APPROVED** [review]

**Comment by colinlyguo** [comment]
I left a new comment in the last merged PR: `blockTrace.WithdrawTrieRoot = withdrawtrie.ReadWTRSlot(rcfg.L2MessageQueueAddress, env.state)` is not controlled by any config now. Is it compatible with other geth configs?

**Review by colinlyguo — APPROVED** [review]

**Review by georgehao — APPROVED** [review]

**Review by icemelon — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
> I left a new comment in the last merged PR: `blockTrace.WithdrawTrieRoot = withdrawtrie.ReadWTRSlot(rcfg.L2MessageQueueAddress, env.state)` is not controlled by any config now. Is it compatible with other geth configs?

I think we don't need to be compatible with other geth config.
and by default `ReadWTRSlot` will return 0 if we don't set up L2MessageQueue contract?

but yeah I do agree it will be great if it can be "controlled by some config"
we can leave it as a future improvement

**Comment by colinlyguo** [comment]
> 

oh, I see, then this modification makes sense since it's just used as a scroll geth.

**Comment by colinlyguo** [comment]
> > I left a new comment in the last merged PR: `blockTrace.WithdrawTrieRoot = withdrawtrie.ReadWTRSlot(rcfg.L2MessageQueueAddress, env.state)` is not controlled by any config now. Is it compatible with other geth configs?
> 
> I think we don't need to be compatible with other geth config. and by default `ReadWTRSlot` will return 0 if we don't set up L2MessageQueue contract?
> 
> but yeah I do agree it will be great if it can be "controlled by some config" we can leave it as a future improvement

oh, I see, then this modification makes sense since it's just used as a scroll geth.

**Pull request merged**
