### PR TITLE
feat(zktrie): upgrade to 0.8.2

### PR DESCRIPTION
**Pull request by omerfirmak**

### CODE REVIEW

**Comment by lispc** [comment]
follower mgasps from 5 -> 15.   Much better.

**Comment by lispc** [comment]
worth a new release for partners.

**Comment by 0xmountaintop** [comment]
some tests fail

**Comment by omerfirmak** [comment]
> some tests fail

should be good now.

**Review by 0xmountaintop — DISMISSED** [review]

**Review by 0xmountaintop — DISMISSED** [review]

**Review by noel2004 — DISMISSED** [review]

**Pull request merged**
