### PR TITLE
update rollup verifier

### PR DESCRIPTION
**Pull request by colinlyguo**
## 1. Purpose or design rationale of this PR

update l2geth verifier.

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] feat: A new feature

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
make mockccc_docker fails.

I tested it and it can work if we upgrade the base image to ubuntu 22:04

**Comment by colinlyguo** [comment]
> make mockccc_docker fails.
> 
> I tested it and it can work if we upgrade the base image to ubuntu 22:04

also fixed this in this commit: https://github.com/scroll-tech/go-ethereum/pull/930/commits/52c5ac4a75f487c759242ce6292e50a6487631f1
missed an env during building and linking: ENV CGO_LDFLAGS="-ldl", I guess ubuntu 22.04 has this as a default.

**Comment by 0xmountaintop** [comment]
> > make mockccc_docker fails.
> > I tested it and it can work if we upgrade the base image to ubuntu 22:04
> 
> also fixed this in this commit: [52c5ac4](https://github.com/scroll-tech/go-ethereum/commit/52c5ac4a75f487c759242ce6292e50a6487631f1) missed an env during building and linking: ENV CGO_LDFLAGS="-ldl", I guess ubuntu 22.04 has this as a default.

https://github.com/scroll-tech/go-ethereum/blob/syncUpstream/replace_package_update_verifier/build/ci.go#L273-L277 also has logic similar to this, do you think we can combine them? (I tried before and didn't manage to make it work)

**Comment by 0xmountaintop** [comment]
> > > make mockccc_docker fails.
> > > I tested it and it can work if we upgrade the base image to ubuntu 22:04
> > 
> > 
> > also fixed this in this commit: [52c5ac4](https://github.com/scroll-tech/go-ethereum/commit/52c5ac4a75f487c759242ce6292e50a6487631f1) missed an env during building and linking: ENV CGO_LDFLAGS="-ldl", I guess ubuntu 22.04 has this as a default.
> 
> https://github.com/scroll-tech/go-ethereum/blob/syncUpstream/replace_package_update_verifier/build/ci.go#L273-L277 also has logic similar to this, do you think we can combine them? (I tried before and didn't manage to)

fixed in https://github.com/scroll-tech/go-ethereum/pull/930/commits/873f351aa7a34b4b01eb795c2d52179b812b4785
(this time I manage to make it work)

and I tested and don't think we need to add `CGO_LDFLAGS` in dockerfile

**Comment by colinlyguo** [comment]
> > > > make mockccc_docker fails.
> > > > I tested it and it can work if we upgrade the base image to ubuntu 22:04
> > > 
> > > 
> > > also fixed this in this commit: [52c5ac4](https://github.com/scroll-tech/go-ethereum/commit/52c5ac4a75f487c759242ce6292e50a6487631f1) missed an env during building and linking: ENV CGO_LDFLAGS="-ldl", I guess ubuntu 22.04 has this as a default.
> > 
> > 
> > https://github.com/scroll-tech/go-ethereum/blob/syncUpstream/replace_package_update_verifier/build/ci.go#L273-L277 also has logic similar to this, do you think we can combine them? (I tried before and didn't manage to)
> 
> fixed in [873f351](https://github.com/scroll-tech/go-ethereum/commit/873f351aa7a34b4b01eb795c2d52179b812b4785) (this time I manage to make it work)
> 
> and I tested and don't think we need to add `CGO_LDFLAGS` in dockerfile

makes sense.

**Pull request merged**
