### PR TITLE
feat(tx-pool): fast reject transactions that cannot fit into a block

### PR DESCRIPTION
**Pull request by colinlyguo**
## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] feat: A new feature

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [x] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [x] This PR is not a breaking change

### CODE REVIEW

**Review by georgehao — DISMISSED** [review]

**Comment by georgehao** [comment]
I think also need to catch `errors.New("tx too big")` error

**Comment by colinlyguo** [comment]
> I think also need to catch `errors.New("tx too big")` error

if `if !pool.chainconfig.Scroll.IsValidBlockSize(tx.Size()) {` can catch all cases that "one tx cannot fit into a block", then we don't need to catch `errors.New("tx too big")` error for the moment, because these txs can at least fit into an empty block.

**Comment by georgehao** [comment]
if you don't deal with the error, the exist error tx will stay in the txpool forever

**Comment by omerfirmak** [comment]
A reboot will get rid of those txns, it is fine.

**Review by omerfirmak — DISMISSED** [review]
It might be nice to add a test to avoid a regression in the future

**Review by 0xmountaintop — DISMISSED** [review]

**Comment by colinlyguo** [comment]
> It might be nice to add a test to avoid a regression in the future

added in [9cc2719](https://github.com/scroll-tech/go-ethereum/pull/1042/commits/9cc27192ec23673f7e296808c81e1abf907847a6).

**Review by omerfirmak — DISMISSED** [review]

**Comment by colinlyguo** [comment]
> if you don't deal with the error, the exist error tx will stay in the txpool forever

makes sense. I also believe reboot and repropagation (then rejection by tx pool) can resolve this.

**Review by Thegaram — DISMISSED** [review]

**Review by omerfirmak — APPROVED** [review]

**Review by georgehao — APPROVED** [review]

**Pull request merged**
