### PR TITLE
fix(jenkins): change tag jenkinsfile docker build script

### PR DESCRIPTION
**Pull request by ChuhanJin**
description:
current script will run failed with some tag name

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
I don't see the reason for this change?

**Comment by ChuhanJin** [comment]
> I don't see the reason for this change?

There is a strange error on jenkins with current script, looks like the build command will always be this:

`+ docker build -t scrolltech/l2geth:prealpha-v5.1`
and error is :
"docker build" requires exactly 1 argument.

I also dont know why, because in the script the command should end with a . like this :
`
 sh "docker build -t scrolltech/l2geth:${TAGNAME} ."`
 
 In order to fix it. I decide to change the build command

**Comment by 0xmountaintop** [comment]
yes but we can build [prealpha-v5.0](https://github.com/scroll-tech/go-ethereum/releases/tag/prealpha-v5.0) & [prealpha-v4.4](https://github.com/scroll-tech/go-ethereum/releases/tag/prealpha-v4.4)?

and I just tried pushing a tag but it doesn't trigger building anymore

**Comment by colinlyguo** [comment]
I think it's the tag I added contains some unexpected characters.

**Review by 0xmountaintop — APPROVED** [review]

**Pull request merged**
