### PR TITLE
add account_proof for `sstore` & `sload` in trace

### PR DESCRIPTION
**Pull request by 0xmountaintop**
also update in [notion doc](https://www.notion.so/EVM-Trace-2e476641b6484b71a029c868516ad7b2)

### CODE REVIEW

**Comment by ChuhanJin** [comment]
Can one of the admins verify this patch?

**Comment by noel2004** [comment]
~~LGTM. But I guess we still need the roothash of account trie to complete the information which MPT circuit needed. May be we can add one more field in the extraData structure?~~

sorry this may not work because calling GetProof from the account trie just access the state before tx begins... account trie is not updated among execution

**Review by mask-pp — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
closed in favor of https://github.com/scroll-tech/go-ethereum/pull/46

**Comment by HAOYUatHZ** [comment]
closed in favor of https://github.com/scroll-tech/go-ethereum/pull/46

**Pull request closed without merging**
